apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-demo
  name: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - image: registry.rigt.online/utils/demo:1
        name: demo
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

