apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: ahmadzana
        # The Github repository
        repo: argocd
        tokenRef:
          secretName: github-classic
          key: secret
      requeueAfterSeconds: 60

  template:
    metadata:
      name: 'myapp-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/ahmadzana/argocd.git'
        targetRevision: '{{head_sha}}'
        path: kubernetes/
        kustomize:
          nameSuffix: '{{branch}}'
          commonLabels:
            app.kubernetes.io/instance: '{{branch}}-{{number}}'
          images:
          - registry.rigt.online/utils/demo:1
      project: "demo-app"
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-app